### ISSUE TITLE
Missing buttons

### ISSUE THREAD

**Issue by josephharkins** [Antes/Lunarfall#5]
Great theme Antes! I have installed it on a RC2 install :-)

I have found an error: there are some buttons not showing, post edit / modify buttons.

Here are some related errors:

- 2: Invalid argument supplied for foreach()
- 8: Undefined index: richedit_buttons
- 8: Undefined index: quickbuttons
- 8: Undefined index: can_disable_announce
- 8: Undefined index: show_links

**Comment by XinYenFon** [comment]
Hmm... can you test the theme with cutting edge build (aka GitHub) ? 

> https://github.com/SimpleMachines/SMF2.1

If still exist, let me know... But I suspect changes between RC2 & RC3 (not yet released) significant enough to break the theme.

You can also try to use v0.6.4 and look... Unfortunately one of the issues with beta/rc releases changes breaks old versions time to time.

**Comment by josephharkins** [comment]
Yes, excellent Antes, updating to the latest github release fixed the visible issues.  I will let you know if anything else pops up. Well done!

**Comment by XinYenFon** [comment]
enjoy the theme, thanks for taking time :)
